const articles: Record<string, {category:string;title:string;subtitle:string}> = {
  "investidores-planejamento": {category:"Planejamento patrimonial",title:"Como investidores podem utilizar planejamento para ampliar patrimônio",subtitle:"Crescer patrimônio não depende apenas de escolher ativos. Depende de conectar objetivo, prazo, liquidez e capacidade de execução."},
  "empresarios-caixa": {category:"Preservação de caixa",title:"Como empresários podem adquirir ativos sem comprometer todo o caixa",subtitle:"Uma aquisição bem planejada considera o ativo desejado e, ao mesmo tempo, a saúde do fluxo de caixa da operação."},
  "imovel-consorcio": {category:"Aquisições estratégicas",title:"O que avaliar antes de adquirir um imóvel com consórcio",subtitle:"Antes de escolher uma ferramenta, é importante entender o objetivo, o prazo, a liquidez disponível e os cenários possíveis."},
};

export default async function ArticlePage({params}: {params: Promise<{slug:string}>}) {
  const {slug} = await params; const article = articles[slug] ?? {category:"Conteúdos de Felipe",title:"Planejamento patrimonial: clareza para decidir",subtitle:"Uma análise consultiva começa pelo seu objetivo e pelo contexto em que a decisão será tomada."};
  return <main className="reader-page"><header className="reader-header"><a href="/consultores/felipe-soares"><img src="/es11-logo.png" alt="ES11 Capital" /></a><a href="/consultores/felipe-soares/artigos">← Todos os conteúdos</a></header><article className="single-article"><small>{article.category} · Felipe Soares · 6 min de leitura</small><h1>{article.title}</h1><p className="article-subtitle">{article.subtitle}</p><div className="article-rule" /><p>Decisões patrimoniais relevantes pedem uma análise que vá além da comparação imediata entre produtos. O ponto de partida é entender o que você deseja construir, em quanto tempo e com qual impacto sobre a sua liquidez.</p><p>Quando objetivo, prazo e capacidade financeira estão claros, é possível avaliar cenários com mais responsabilidade. Nem sempre existe um único caminho; existem alternativas que podem se adequar melhor ao momento de cada pessoa, família ou empresa.</p><p>Meu papel é ajudar a organizar essa conversa, traduzir impactos e construir um planejamento alinhado ao seu contexto. Estratégia não é promessa de resultado: é clareza para tomar melhores decisões ao longo do tempo.</p><aside><strong>Sobre Felipe Soares</strong><span>Sócio e Consultor Financeiro da ES11 Capital. Atua com estratégias patrimoniais para investidores, empresários, profissionais liberais e famílias.</span><a href="https://wa.me/5511971244859?text=Olá%2C%20Felipe.%20Li%20seu%20artigo%20e%20gostaria%20de%20conversar%20sobre%20planejamento%20patrimonial." target="_blank" rel="noreferrer">Conversar com Felipe →</a></aside></article></main>;
}
