import { articles, consultant, decisions, faq, specialties } from "./lib/felipe";
import { SiteHeader } from "./components/SiteHeader";
import { ScrollReveal } from "./components/ScrollReveal";

export default function Home() {
  const profileJsonLd = { "@context": "https://schema.org", "@type": ["ProfilePage", "Person"], name: consultant.name, jobTitle: consultant.role, url: consultant.profileUrl, image: consultant.image, worksFor: { "@type": "Organization", name: "ES11 Capital", url: "https://www.es11capital.com.br/" }, sameAs: ["https://www.instagram.com/felipennsoares/", "https://www.instagram.com/es11capital/"] };
  return (
    <main id="inicio">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(profileJsonLd) }} />
      <ScrollReveal />
      <SiteHeader whatsapp={consultant.whatsapp} />

      <section className="hero reveal">
        <div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" />
        <div className="container hero-grid">
          <div className="hero-copy">
            <p className="kicker">CONSULTOR FINANCEIRO · ES11 CAPITAL</p>
            <h1>Felipe Soares</h1>
            <p className="hero-title">Estratégias patrimoniais para investidores e empresários que desejam crescer preservando liquidez.</p>
            <p className="hero-description">Atendimento consultivo para estruturar aquisições, ampliar patrimônio e transformar objetivos em um planejamento de longo prazo.</p>
            <div className="hero-actions"><a className="gold-button" data-position="hero" href={consultant.whatsapp} target="_blank" rel="noreferrer">Agendar conversa com Felipe <b aria-hidden="true">→</b></a><a className="quiet-link" href="#como-funciona">Conhecer o atendimento <b aria-hidden="true">↓</b></a></div>
            <div className="hero-points"><span>Atendimento consultivo</span><span>São Paulo, SP · todo o Brasil</span><span>ES11 Capital</span></div>
          </div>
          <div className="hero-photo-wrap"><div className="photo-outline" /><img className="hero-photo" src="/felipe-soares-retrato-hq.webp" alt="Felipe Soares, sócio e consultor financeiro da ES11 Capital" /><div className="photo-label"><strong>Felipe Soares</strong><small>Estratégia para o seu momento</small></div></div>
        </div>
      </section>

      <section className="about section reveal" id="sobre"><div className="container about-grid"><div><p className="section-tag">SOBRE FELIPE</p><h2>Patrimônio não se constrói por acaso. <em>Ele ganha direção.</em></h2></div><div className="about-copy"><p>Sou sócio da ES11 Capital e atuo com estratégias patrimoniais voltadas para pessoas e empresas que desejam construir patrimônio de forma inteligente.</p><p>Minha trajetória começou na área comercial, onde desenvolvi uma visão consultiva focada em entender os objetivos de cada cliente e encontrar as melhores soluções. Hoje, ajudo clientes a transformar planejamento financeiro em crescimento patrimonial por meio de estratégias personalizadas.</p><blockquote>“Meu trabalho começa antes da apresentação de qualquer produto: começa entendendo o objetivo, o momento financeiro e os planos futuros do cliente.”</blockquote></div></div></section>

      <section className="difference reveal"><div className="container difference-inner"><p className="section-tag">O DIFERENCIAL</p><h2>Não é sobre apresentar um produto. É sobre construir uma estratégia que faça sentido para você.</h2><p>Meu compromisso é oferecer um atendimento consultivo e personalizado, acompanhando sua evolução e ajudando na tomada de decisões com mais segurança.</p></div></section>

      <section className="audiences section reveal"><div className="container"><div className="section-heading"><div><p className="section-tag light">PARA QUEM É O ATENDIMENTO</p><h2>Para quem pensa patrimônio <em>com seriedade.</em></h2></div><p>O ponto de partida é entender o que você deseja construir, adquirir ou organizar - e definir caminhos compatíveis com sua realidade.</p></div><div className="audience-grid"><article><span>01 / PRIORIDADE</span><h3>Investidores</h3><p>Para quem deseja ampliar patrimônio, avaliar aquisições e usar tempo, liquidez e oportunidades de forma estratégica.</p></article><article><span>02</span><h3>Empresários e profissionais liberais</h3><p>Para estruturar ativos e crescimento sem comprometer o fluxo pessoal ou empresarial.</p></article><article><span>03</span><h3>Famílias e empresas</h3><p>Para transformar projetos de imóveis, veículos, frota ou equipamentos em planejamento de longo prazo.</p></article></div></div></section>

      <section className="decisions section reveal"><div className="container decisions-grid"><div className="decision-image"><img src="/felipe-soares-es11-hq.webp" alt="Felipe Soares em reunião na ES11 Capital" /><span>ES11 CAPITAL</span></div><div><p className="section-tag">EM QUAIS DECISÕES POSSO AJUDAR</p><h2>Clareza antes da sua próxima decisão patrimonial.</h2><div className="decision-list">{decisions.map((decision) => <span key={decision}>{decision}</span>)}</div></div></div></section>

      <section className="specialties section reveal" id="especialidades"><div className="container"><p className="section-tag">ESPECIALIDADES</p><div className="specialty-heading"><h2>Estratégias que respeitam o seu momento e <em>o seu futuro.</em></h2><a className="quiet-link navy-link" href={consultant.whatsapp} target="_blank" rel="noreferrer">Falar sobre meu objetivo <b aria-hidden="true">→</b></a></div><div className="specialty-grid">{specialties.map((item)=><article key={item.number}><span>{item.number}</span><i /><h3>{item.title}</h3><p>{item.text}</p><b aria-hidden="true">↗</b></article>)}</div></div></section>

      <section className="method section reveal" id="como-funciona"><div className="container"><div className="method-heading"><div><p className="section-tag light">COMO FUNCIONA</p><h2>Uma conversa estratégica para clarear <em>seu próximo movimento.</em></h2></div><p>Meu atendimento é estratégico, próximo e didático. Antes de apresentar qualquer solução, busco entender objetivos, realidade financeira e planos futuros.</p></div><div className="steps">{[["01","Objetivo","Você apresenta o que deseja adquirir, construir ou organizar."],["02","Diagnóstico","Entendemos momento financeiro, liquidez, prazo e prioridades."],["03","Cenários","Avaliamos alternativas e seus possíveis impactos."],["04","Estratégia","Apresentamos caminhos que podem fazer sentido."],["05","Acompanhamento","Caso avance, acompanho a execução da estratégia."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><a className="gold-button method-button" data-position="method" href={consultant.whatsapp} target="_blank" rel="noreferrer">Quero conversar com Felipe <b aria-hidden="true">→</b></a></div></section>

      <section className="es11 section reveal"><div className="container es11-inner"><div><img src="/es11-logo.png" alt="ES11 Capital" /><p className="section-tag">A ESTRUTURA DA ES11 CAPITAL</p><h2>Atendimento pessoal com uma estrutura maior por trás.</h2></div><p>A ES11 Capital atua com planejamento e estruturação patrimonial para investidores, empresários, profissionais liberais, famílias e empresas. Antes de recomendar qualquer solução, são considerados objetivo, liquidez, prazo, capacidade financeira, oportunidades e riscos.</p><a className="quiet-link navy-link" data-position="institutional" href="https://www.es11capital.com.br/" target="_blank" rel="noreferrer">Conhecer a ES11 Capital <b aria-hidden="true">↗</b></a></div></section>

      <section className="content section reveal" id="conteudos"><div className="container"><div className="section-heading content-heading"><div><p className="section-tag">CONTEÚDOS DE FELIPE</p><h2>Ideias para decidir <em>com mais clareza.</em></h2></div><a className="quiet-link navy-link" href="/consultores/felipe-soares/artigos">Ver todos os artigos <b aria-hidden="true">→</b></a></div><div className="article-grid">{articles.slice(0, 3).map((article, index)=><article key={article.slug}><div className={`article-visual visual-${index+1}`}><img src={article.image} alt={article.imageAlt} /><span>{article.category}</span></div><div className="article-body"><small>{new Date(article.publishedAt).toLocaleDateString("pt-BR")} · {article.readingTime}</small><h3>{article.title}</h3><a data-article-cta="true" href={`/consultores/felipe-soares/artigos/${article.slug}`}>Ler artigo <b aria-hidden="true">→</b></a></div></article>)}</div></div></section>

      <section className="faq section reveal" id="duvidas"><div className="container faq-grid"><div><p className="section-tag">DÚVIDAS COMUNS</p><h2>Antes de decidir, <em>é natural perguntar.</em></h2><p>Se o seu objetivo ainda não está totalmente claro, a conversa é justamente o lugar para começar.</p></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<b aria-hidden="true">+</b></summary><p>{a}</p></details>)}</div></div></section>

      <section className="final-cta reveal"><div className="container final-cta-inner"><p className="section-tag light">SEU PRÓXIMO PASSO</p><h2>Objetivos claros. <em>Resultados construídos com estratégia.</em></h2><p>Se você tem um objetivo, mas ainda não sabe qual é o melhor caminho para alcançá-lo, conte comigo. Vamos analisar sua situação e montar um planejamento para o seu momento.</p><a className="gold-button" data-position="final-cta" href={consultant.whatsapp} target="_blank" rel="noreferrer">Agendar conversa com Felipe <b aria-hidden="true">→</b></a></div></section>

      <footer><div className="container footer-grid"><div><img src="/es11-logo.png" alt="ES11 Capital" /><p>Felipe Soares<br /><span>Sócio e Consultor Financeiro</span></p></div><div><small>CONTATO</small><a data-position="footer" href={consultant.whatsapp} target="_blank" rel="noreferrer">(11) 97124-4859</a><p>São Paulo, SP · atendimento em todo o Brasil</p></div><div><small>SIGA</small><a data-position="footer" href="https://www.instagram.com/felipennsoares/" target="_blank" rel="noreferrer">@felipennsoares ↗</a><a data-position="footer" href="https://www.instagram.com/es11capital/" target="_blank" rel="noreferrer">@es11capital ↗</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Felipe Soares · ES11 Capital</span><span>A análise realizada pela ES11 Capital é personalizada e consultiva. Não há promessa de prazo de contemplação, rentabilidade ou resultado financeiro.</span></div></footer>
    </main>
  );
}

